/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.VOI;

import com.mycompany.VOI.VehiclesOfInterestController;
import java.net.URL;
import com.mycompany.VOI.Dashboard;
import com.mycompany.VOI.ReasonsForInterest;
import com.mycompany.VOI.MakesAndModels;
import javax.swing.JOptionPane;



/**
 *
 * @author sameen_shahbaz
 */

public class VehiclesOfInterest extends javax.swing.JFrame {
    VehiclesOfInterestController controller = new VehiclesOfInterestController();

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VehiclesOfInterest.class.getName());

    /**
     * Creates new form VehiclesOfInterest
     */

    public VehiclesOfInterest() {
	
        initComponents();
	loadVehicleTable();
	setupButtonListeners();
	setLocationRelativeTo(null);
   	setAlwaysOnTop(true);
    	toFront();
    }

    public void loadVehicleTable() {
   	 String[][] allVehicles = controller.allVehicleOfInterest();

    	 String[] columns = {
        	"License Plate", "Reason", "Make", "Model",
        	"Year", "Color", "Owner Name", "Owner Phone"
   	 };

    	 javax.swing.table.DefaultTableModel model =
       	      new javax.swing.table.DefaultTableModel(allVehicles, columns);

   	 tblVehicles.setModel(model);
     }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehicles = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Dashboard");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(147, 220, 255));
        jButton2.setText("Vehicles Of Interest");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setFocusPainted(false);

        jButton3.setText("Reasons For Interest");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);

	jButton3.addActionListener(new java.awt.event.ActionListener() {
    	    public void actionPerformed(java.awt.event.ActionEvent evt) {
        	jButton3ActionPerformed(evt);
    	    }
	});


        jButton4.setText("Makes and Models");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);

	jButton4.addActionListener(new java.awt.event.ActionListener() {
   	    public void actionPerformed(java.awt.event.ActionEvent evt) {
        	jButton4ActionPerformed(evt);
    	    }
	});	

        jButton5.setText("Help");
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
	jButton5.addActionListener(evt -> jButton5ActionPerformed(evt));

        jButton6.setText("Logout");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
	jButton6.addActionListener(evt -> jButton6ActionPerformed(evt));

     

        /* jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/VOI/Resources/PoliceDeptIcon(ressized).png"))); // NOI18N */

	
	try {
    	    java.net.URL icon1 = getClass().getResource("/com/mycompany/VOI/Resources/PoliceDeptIcon_resized.png");
   	    if (icon1 != null) {
       	        java.awt.image.BufferedImage img = javax.imageio.ImageIO.read(icon1);
        	if (img != null) {
           	    jLabel1.setIcon(new javax.swing.ImageIcon(img));
           	    System.out.println("jLabel1 icon set successfully.");
       	        } else {
            	    System.err.println("ImageIO.read returned null for: " + icon1);
       	        }
    	     } else {
        	 System.err.println("Image not found: PoliceDeptIcon_resized.png");
   	     }
	} catch (Exception e) {
   	    System.err.println("Exception while loading jLabel1 image:");
    	    e.printStackTrace();
	}


        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addComponent(jButton5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(353, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jPanel3.setBackground(new java.awt.Color(142, 217, 255));

        tblVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Plate Number", "Reason", "Make", "Model", "Year", "Color", "Owner's Name", "Owner's Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVehicles);

        jButton7.setBackground(new java.awt.Color(142, 220, 255));
        jButton7.setText("Add Vehicle");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton8.setBackground(new java.awt.Color(142, 220, 255));
        jButton8.setText("Delete Vehicle");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton9.setBackground(new java.awt.Color(142, 220, 255));
        jButton9.setText("Edit Vehicle");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 93, 560, 380));

        /* jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/VOI/Screenshot 2025-06-08 at 7.24.00 PM.png"))); // NOI18N */

	try {
    	    java.net.URL icon2 = getClass().getResource("/com/mycompany/VOI/Resources/user.png");
            if (icon2 != null) {
       	        java.awt.image.BufferedImage img = javax.imageio.ImageIO.read(icon2);
       	        if (img != null) {
                    jLabel2.setIcon(new javax.swing.ImageIcon(img));
           	    System.out.println("jLabel2 icon set successfully.");
        	} else {
           	    System.err.println("ImageIO.read returned null for: " + icon2);
        	}
   	    } else {
        	System.err.println("Image not found: user.png");
    	    }
	 } catch (Exception e) {
    	    System.err.println("Exception while loading jLabel2 image:");
    	    e.printStackTrace();
	 }


        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 50, 30));

        /* jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/VOI/English2.png"))); // NOI18N */

	try {
    	    java.net.URL icon3 = getClass().getResource("/com/mycompany/VOI/Resources/English2.png");
   	    if (icon3 != null) {
            	java.awt.image.BufferedImage img = javax.imageio.ImageIO.read(icon3);
        	if (img != null) {
           	    jLabel3.setIcon(new javax.swing.ImageIcon(img));
           	    System.out.println("jLabel3 icon set successfully.");
        	} else {
           	   System.err.println("ImageIO.read returned null for: " + icon3);
       	        }
    	    } else {
        	System.err.println("Image not found: English2.png");
   	    }
	} catch (Exception e) {
    	   System.err.println("Exception while loading jLabel3 image:");
    	   e.printStackTrace();
	}



        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   	// Dashboard button

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
   	 new Dashboard().setVisible(true);
   	 this.dispose();
	}

	// Vehicles Of Interest button

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
   	 new VehiclesOfInterest().setVisible(true);
   	 this.dispose();
	}

	// Reasons For Interest button

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
   	 new ReasonsForInterest().setVisible(true);
    	 this.dispose();
	}

	// Makes and Models button

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
  	  new MakesAndModels().setVisible(true);
    	  this.dispose();
	}

	// Help button

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
   	 javax.swing.JOptionPane.showMessageDialog(
       	     this,
       	     "Vehicles Of Interest System\n\nUse the sidebar to manage vehicles, reasons and vehicle makes/models.",
             "Help",
             javax.swing.JOptionPane.INFORMATION_MESSAGE
    	 );
	}

	// Logout button
	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
    		System.exit(0);
	}


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VehiclesOfInterest().setVisible(true));
    }


    private void setupButtonListeners() {

    // Add Vehicle button (jButton7)

    jButton7.addActionListener(e -> {
        String licensePlate = javax.swing.JOptionPane.showInputDialog(this, "Enter License Plate:");
        if (licensePlate == null || licensePlate.trim().isEmpty()) return;

        String reason = javax.swing.JOptionPane.showInputDialog(this, "Enter Reason:");
        String make = javax.swing.JOptionPane.showInputDialog(this, "Enter Make:");
        String model = javax.swing.JOptionPane.showInputDialog(this, "Enter Model:");
        String vehYear = javax.swing.JOptionPane.showInputDialog(this, "Enter Year:");
        String color = javax.swing.JOptionPane.showInputDialog(this, "Enter Color:");
        String ownersName = javax.swing.JOptionPane.showInputDialog(this, "Enter Owner's Name:");
        String ownersPhone = javax.swing.JOptionPane.showInputDialog(this, "Enter Owner's Phone:");

        controller.createVehicleOfInterest(licensePlate, reason, make, model, vehYear, color, ownersName, ownersPhone);

        loadVehicleTable(); // refresh table after adding 
    });

    // Edit Vehicle button (jButton9)



    jButton9.addActionListener(e -> {
	 int selectedRow = tblVehicles.getSelectedRow();
    	 if (selectedRow == -1) {
       	    JOptionPane.showMessageDialog(this, "Please select a vehicle to edit.");
            return;
    	 }

   	 // Get original license plate (primary key)
   	 String licensePlate = (String) tblVehicles.getValueAt(selectedRow, 0);

    	// Get current values from the table
    	 String currentReason = (String) tblVehicles.getValueAt(selectedRow, 1);
    	 String currentMake = (String) tblVehicles.getValueAt(selectedRow, 2);
    	 String currentModel = (String) tblVehicles.getValueAt(selectedRow, 3);
    	 String currentYear = (String) tblVehicles.getValueAt(selectedRow, 4);
    	 String currentColor = (String) tblVehicles.getValueAt(selectedRow, 5);
   	 String currentOwner = (String) tblVehicles.getValueAt(selectedRow, 6);
   	 String currentPhone = (String) tblVehicles.getValueAt(selectedRow, 7);

    	// Prompt for new values
    	String reason = JOptionPane.showInputDialog(this, "Edit Reason:", currentReason);
    	String make = JOptionPane.showInputDialog(this, "Edit Make:", currentMake);
    	String model = JOptionPane.showInputDialog(this, "Edit Model:", currentModel);
    	String vehYear = JOptionPane.showInputDialog(this, "Edit Year:", currentYear);
    	String color = JOptionPane.showInputDialog(this, "Edit Color:", currentColor);
    	String ownersName = JOptionPane.showInputDialog(this, "Edit Owner Name:", currentOwner);
    	String ownersPhone = JOptionPane.showInputDialog(this, "Edit Owner Phone:", currentPhone);

    	// Send update to DB
    	controller.updateVehicleOfInterest(licensePlate, reason, make, model, vehYear, color, ownersName, ownersPhone);

    	// Refresh the table
    	loadVehicleTable();
    });
	


    // Delete Vehicle button (jButton8)

    jButton8.addActionListener(e -> {
        int selectedRow = tblVehicles.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a vehicle to delete.");
            return;
        }
        String licensePlate = (String) tblVehicles.getValueAt(selectedRow, 0);
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete vehicle with license plate: " + licensePlate + "?",
                "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            controller.deleteVehicleOfInterest(licensePlate);
            loadVehicleTable();
        }
    });
}

	

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVehicles;
    // End of variables declaration//GEN-END:variables
}
